name: dart_nats
description: A Dart client for the NATS messaging system. Design to use with Dart and flutter.
version: 0.5.1
homepage: https://github.com/chartchuo
repository: https://github.com/chartchuo/dart-nats

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.11.0
dependencies: 
  base32: ^2.1.3
  # cryptography: ^2.0.5
  ed25519_edwards: ^0.3.1
  mutex: ^3.0.0
  web_socket_channel: ^2.2.0
