name: dart_nats
description: A Dart client for the NATS messaging system. Design to use with Dart and flutter.
version: 0.1.7
homepage: https://github.com/chartchuo
repository: https://github.com/chartchuo/dart-nats

environment:
  sdk: ">=2.1.0 <3.0.0"

# dependencies:

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0
